stages:
  - run

variables:
  REPOSYNC_OPTS:
    value: "-v"
    description: Additional options passed to reposync

run:
  image:
    name: artifacts-cr.eas.wwu.edu/eas/reposync:latest
    entrypoint: [""]
  stage: run
  tags:
    - docker
  cache:
    paths:
      - .gradle
      - build
      - repos
  before_script:
    # Set LANG to avoid local warnings from git commands
    - export LANG=C

    # Avoid reloading gradle dependencies on every run
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - mkdir -p $GRADLE_USER_HOME
    - |
      [ -r "$GRADLE_USER_HOME/gradle.properties" ] || cat > $GRADLE_USER_HOME/gradle.properties <<EOF
      easNexusUrl=https://artifacts.eas.wwu.edu/repository
      EOF

    # Start ssh-agent
    - "eval $(ssh-agent -s)"

  # Add key to ssh-agent
  - mkfifo keyfile
  - chmod 600 keyfile
  - 'echo "$SSH_PRIVATE_KEY" > keyfile &'
  - ssh-add keyfile
  - rm keyfile

    # Set up server hostkeys
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo "$SSH_SERVER_HOSTKEYS" > ~/.ssh/known_hosts'
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - when: manual
  script:
    - './gradlew run --args="$REPOSYNC_OPTS -t $GITLAB_API_KEY -r ./repos"'
  allow_failure: false
  environment:
    name: production
    url: https://git.eas.wwu.edu/eas/ellucian
