#!/bin/bash

usage () {
	echo "Fix Ellucian submodule repository URLs.  Run from the top level directory of the repository"
	echo "after running \"git submodule init\"."
	echo
	echo "usage: $(basename $0) [ options ]"
	echo
	echo "   -h  help (this message)"
	echo
	exit 1
} >&2

while getopts h opt; do
	case "$opt" in
		*)
			usage
			;;
    esac
done

shift $((OPTIND-1))
if [ "$#" -gt 0 ]; then
	usage
fi

case $(uname -s) in
    Linux|MINGW*|CYGWIN*)
        I_OPT="-i.bak"
        ;;
    *BSD|Darwin)
        I_OPT="-i .bak"
        ;;
    *)
        echo "I don't know how to deal with $(uname -s), you're on your own"
        exit 1
        ;;
esac

if [ ! -w .git/config ]; then
	echo ".git/config not found, is your current directory the top level directory of the repository?" >&2
	echo >&2
	usage
fi

sed -i .bak \
	-e '/url = \(ssh:\/\/\)\{0,1\}git@devgit1\.ellucian\.com\//s||---GitLabMarKer---|' \
	-e '/---GitLabMarKer---/s|/|-|g' \
	-e '/---GitLabMarKer---/s||url = ssh://git@git.eas.wwu.edu:Ellucian/|' \
	.git/config

if [ $? -ne 0 ]; then
	echo "sed failed, check .git/config, backup is in .git/config.bak" >&2
fi
